// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0240cSV9HrWNrrM9DNNLlIUcca-oa35Y',
    appId: '1:616329688006:web:35efd7b028a1d01f1878c7',
    messagingSenderId: '616329688006',
    projectId: 'gym-app-23237',
    authDomain: 'gym-app-23237.firebaseapp.com',
    storageBucket: 'gym-app-23237.firebasestorage.app',
    measurementId: 'G-CHXQEQYVPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgooSUsAlENJLu9bsjsVibG1g-b5Qkzik',
    appId: '1:616329688006:android:f52055bb9e1055901878c7',
    messagingSenderId: '616329688006',
    projectId: 'gym-app-23237',
    storageBucket: 'gym-app-23237.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGZ5dUQ6JKPQHu_K1ZJsC9nDSPUGPu-c8',
    appId: '1:616329688006:ios:83c68dc5b1ff12b61878c7',
    messagingSenderId: '616329688006',
    projectId: 'gym-app-23237',
    storageBucket: 'gym-app-23237.firebasestorage.app',
    iosBundleId: 'com.example.gymApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGZ5dUQ6JKPQHu_K1ZJsC9nDSPUGPu-c8',
    appId: '1:616329688006:ios:83c68dc5b1ff12b61878c7',
    messagingSenderId: '616329688006',
    projectId: 'gym-app-23237',
    storageBucket: 'gym-app-23237.firebasestorage.app',
    iosBundleId: 'com.example.gymApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0240cSV9HrWNrrM9DNNLlIUcca-oa35Y',
    appId: '1:616329688006:web:967d34304aca1ec61878c7',
    messagingSenderId: '616329688006',
    projectId: 'gym-app-23237',
    authDomain: 'gym-app-23237.firebaseapp.com',
    storageBucket: 'gym-app-23237.firebasestorage.app',
    measurementId: 'G-Q478SQZZBN',
  );
}
